#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v ibus >/dev/null 2>&1; then
            ibus write-cache --system >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
